[logging]
dump-workload = false

[game]
host = "::1"
port = 25565

[experiment]
id = 9
[experiment.params]
bots = 50
joininterval = 5
numbotsperjoin = 5
duration = 350

spawnAnchor = true

spikeDelayInSeconds = 170
spikeDurationInSeconds = 60
spikePeakPlayers = 66
